--- 
- :name: mysql
- :name: BlueCloth
- :version: = 4.2.2
  :name: RedCloth
- :version: = 2.1.2
  :name: builder
- :version: = 2.1.0
  :name: gravtastic
- :version: = 2.2.20
  :name: haml
- :version: = 1.2.4
  :name: json
- :version: = 0.1.5
  :name: has_markup
- :version: = 0.6.5
  :source: http://gems.github.com
  :name: thoughtbot-clearance
- :version: = 1.1.5
  :source: http://gems.github.com
  :name: thoughtbot-pacecar
- :version: = 0.2.2
  :source: http://gems.github.com
  :name: yfactorial-utility_scopes
- :version: = 0.8.5
  :name: josevalim-inherited_resources
- :version: = 0.5.5
  :source: http://gems.github.com
  :name: dancroak-twitter-search
- :version: = 0.0.5
  :name: dancroak-le-git
- :version: = 0.2.8.0
  :name: taf2-curb
- :version: = 0.1.1
  :name: technicalpickles-feedra
- :version: = 2.3.11
  :name: will_paginate
- :version: = 0.2.3
  :name: chronic
- :version: = 2.2.0
  :name: hoptoad_notifier
- :version: = 0.1.2
  :name: truncate_html
- :name: nokogiri
- :name: curb
- :version: ~> 0.8.5
  :name: ri_cal
- :version: 2.3.9
  :name: rails
